name: Auto-Restart Codespace Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'    # every 5 minutes
  workflow_dispatch:         # allows manual run

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
    - name: Restart Codespace
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
        CODESPACE_NAME: fuzzy system
        USERNAME: Hello405p
      run: |
        curl -X POST \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/users/${USERNAME}/codespaces/${CODESPACE_NAME}/start
